### ISSUE TITLE
Проблемы с добавлением зависимостей к проектам на framework-e

### ISSUE THREAD

**Issue by likvidator3301** [skbkontur/cement#104]
Вызов: `cm ref add houston.aspnetcore TargetModule/TargetModule.csproj`

Ошибка: `[WARN] Installation of NuGet packages failed: Could not install package 'Microsoft.AspNetCore 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by KoHHeKT** [comment]
[https://files.slack.com/files-pri/T02A9SVQ1-F01H6HUR588/download/targetmodule.zip](example TargetModule.zip)

**Comment by KoHHeKT** [comment]
Конвертирование csproj в новый формат решает проблему
