### ISSUE TITLE
Добавить фильтр по веткам для cm usages show

### ISSUE THREAD

**Issue by goodoldlameme** [skbkontur/cement#126]
При вызове cm usages show возвращаются использования во всех ветках.
Хочется смотреть использования только в мастерах.

**Comment by KoHHeKT** [comment]
Что за вопрос был? Может надо документацию дописать на будущее?

**Comment by goodoldlameme** [comment]
Закрыла и не стала дополнять, потому что оказалось, что такой тикет уже есть

**Comment by goodoldlameme** [comment]
https://github.com/skbkontur/cement/issues/98
