### ISSUE TITLE
Цемент использует старый MSBuild

### ISSUE THREAD

**Issue by anaym** [skbkontur/cement#127]
В системе установлен MSBuild версии 17.0.0+c9eb9dd64
При этом цемент не видит эту версию и упорно продолжает использовать MSBuild  16.0.461+g6ff56ef63c, из-за чего не может сбилдить код с новыми языковыми фичами.

`set VS150COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin` не помогает

**Comment by KoHHeKT** [comment]
fixed with version 1.0.75
