### ISSUE TITLE
Перенести Samples в организацию skbkontur

### ISSUE THREAD

**Issue by likvidator3301** [skbkontur/cement#138]
Сейчас по умолчанию цемент ссылается на 2 источника модулей - Samples и Vostok
Samples при этом лежат в личном репозитории - https://github.com/KungA/cement-sample-modules

Необходимо перенести их в организацию skbkontur

При этом нужно учесть, что автоматическое обновление цемента не перепишет ссылку

**Comment by ArXa1L** [comment]
Перенесли
