### ISSUE TITLE
Увеличить скорость сборки за счет некопирования лишних dll

### ISSUE THREAD

**Issue by beevee** [skbkontur/cement#24]

**Comment by alexSatov** [comment]
fts deps [bin] (default):  4,8 Gb, build-time: 9:50
fts deps [bin] (lite): 1,64 Gb, build-time: 5:51

**Comment by KungA** [comment]
Есть множество проблем при таком подходе, часть которых мы совсем не умеем решать:
- msbuild может копировать dll-ки транзитивно
- всегда нужно иметь правильные ссылки (решается командами `cm check-deps` и `cm ref fix`)
- есть штуки, которые post-build-event-ом что-нибудь делают (можно выключать их в клиентской конфигурации)
- если мы в начале сбилдили полностью, а потом так, то у нас останутся старые dll-ки (можно удалять старые, но это занимает время)

Фича цемента, не всегда ребилдить все зависимости частично решает проблему долгого билда.
А экономить место кажется не сильно интересным.
