### ISSUE TITLE
cm ref fix doesn't fix ref if it doesn't contain HintPath

### ISSUE THREAD

**Issue by 13xforever** [skbkontur/cement#37]
The problem is this: ReSharper has _helpfully_ fixed a reference to a transient dependency which it found in the bin of the current project, thus adding a `<Reference>` without a `HintPath`.

Both `cm check-deps` and `cm ref fix` ignore this dependency as an extraneous one.

**Comment by KungA** [comment]
Cement is checking and fixing only references to other modules.
References without hint path can lead to `framework directory` or `GAC`.

Possible solution: fix references to existing dll, specified in `module.yaml`.
But we will have many conflicts with `packages` folder (should we ignore it?).

**Comment by 13xforever** [comment]
You know all the dependent modules that are specified in the `module.yaml`, so you can look for and fix only those that are specified there explicitly. I don't see how this will conflict with the `packages` (that are nuget references, and not cement references).

**Comment by KungA** [comment]
Because we had modules with some nuget packages dlls as artifacts, for example
- `cauldron.queryclient\QueryClient\bin\Release\MongoDB.Bson.dll`
- `Newtonsoft.Json.dll\Newtonsoft.Json.dll`

**Comment by KungA** [comment]
Also we can have multiple solutions in one module with cross-links.

**Comment by KungA** [comment]
use new -e key for `cm ref fix` & `cm check-deps`
