### ISSUE TITLE
Cement вынуждает хранить закрытый ключ в незашифрованном виде

### ISSUE THREAD

**Issue by beevee** [skbkontur/cement#39]
(перенес из другого багтрекера)

Как я понял, проблема такая:
1) Cement пользуется git-ом через ssh
2) В таком режиме git не умеет таскать ключи из PuttyAgent-а
3) Поэтому приходится указывать файле в C:\Users\<ИМЯ ПОЛЬЗОВАТЕЛЯ>\.ssh\config путь до файла с закрытым ключом:
Host git.skbkontur.ru
IdentityFile C:\Users\<ИМЯ ПОЛЬЗОВАТЕЛЯ>\.ssh\cement.priv
User git
4) Если этот файл будет зашифрованный, cement не сможет с ним работать. Хотя при этом просто git clone git@git.skbkontur.ru:ke/ke-cm-modules.git запросит пароль для расшифровки ключа и прекрасно отработает
Итого, чтобы пользоваться Cement-ом, я вынужден хранить закрытый ключ для доступа к репозиторию в незашифрованном виде

**Comment by 13xforever** [comment]
1. Агент можно указать изменив переменную окружения
  `GIT_SSH=c:\path\to\plink.exe` (аналогично для `SVN_SSH`)
2. Можно юзать [`ssh-agent`](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement) в более новых версиях Windows
