### ISSUE TITLE
install: nuget packages leak into InstallData properties

### ISSUE THREAD

**Issue by obiwan-smirnobi** [skbkontur/cement#67]
Consider a `module.yaml` example:

```
full-build:
  artifacts:
    - a1
    - nuget SomeNuget1
```

After calling `InstallYamlParser.Get()` I get a InstallData with these properties:
- Artifacts:
  * a1
  * nuget SomeNuget1  
- MainConfigBuildFiles:
  * a1
  * nuget SomeNuget1

It seems, that `nuget SomeNuget1` should not be either in `Artifacts` or in `MainConfigBuildFiles` collections. 

P.S. It's probably a bug, that appeared after merge request #15: [source1](https://github.com/skbkontur/cement/blob/cc24d78c06a42ffaf1f28357aa03df25e9c37aef/Common/YamlParsers/InstallYamlParser.cs#L41), [source2](https://github.com/skbkontur/cement/blob/cc24d78c06a42ffaf1f28357aa03df25e9c37aef/Common/YamlParsers/InstallYamlParser.cs#L48)

**Comment by KungA** [comment]
Yes, it should be only in `NuGetPackages`.
And `- module x` only in `ExternalModules`.

**Comment by obiwan-smirnobi** [comment]
The fix is on the way: [https://github.com/obiwan-smirnobi/cement/commit/8558877a02e35a7bbc8a0b2878e6aa68ec6e973e](8558877a02e35a7bbc8a0b2878e6aa68ec6e973e).
We can deal with it after pull request https://github.com/skbkontur/cement/pull/68

> And `- module x` only in `ExternalModules`.

This works fine 👍
