### ISSUE TITLE
Удалять bin и obj перед сборкой у проектов на .NET Standard

### ISSUE THREAD

**Issue by PhonkX** [skbkontur/cement#93]
Бывает, что при повторной сборке с помощью cement проектов на .NET Standard появляются ошибки вида "error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Ошибки нестабильные, на одном и том же проекте ошибка может повторяться, а может и не повторяться. Известно, что при сборке в чистую папку такого не происходит.
Способы с манипуляцией csproj (добавление reference на netstandard или явное включение автогенерации binding redirects) не помогают. Не помогает и выполнение dotnet restore/dotnet clean перед сборкой.
При этом хорошо работает полное удаление папок bin и obj.
Хочется, чтобы в Cement была возможность перед билдом sln с проектами на .NET Standard удалять bin и obj. Возможно, такая возможность должна включаться по флагу.

**Comment by ArXa1L** [comment]
Стоит обратить внимание, что в каждом отдельном `*.csproj`-файле могут быть переопределены msbuild-параметры `OutputPath` (по умолчанию `bin/$(Configuration)`) и IntermediateOutputPath (по умолчанию `obj/$(Configuration)`).

**Comment by KungA** [comment]
Ещё проще git clean позвать
